# Generated by Django 4.2.7 on 2023-12-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_registeredevents_classticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registeredevents',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
