# Generated by Django 4.2.7 on 2023-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_address_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Event Title')),
                ('images', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Event Image')),
            ],
        ),
    ]
